name: Documentation Improvement
description: Create a report to help us improve the documentation. Alternatively, you can just open a pull request with the suggested change.
title: "doc: "
labels: ["documentation"]
assignees: tomcdj71

body:
  - type: markdown
    attributes:
      value: |
        **Documentation Improvement**

        Thank you for helping us improve our documentation!

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we reach you if we have questions about your suggestion?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    id: documentation-section
    attributes:
      label: Documentation Section
      description: Please specify the section or parts of the documentation that you are suggesting to improve.
      placeholder: Section or parts of the documentation.
    validations:
      required: true

  - type: textarea
    id: current-issues
    attributes:
      label: Current Issues
      description: Describe any current issues or inaccuracies you've found in the documentation.
      placeholder: Current issues or inaccuracies...
    validations:
      required: true

  - type: textarea
    id: suggested-improvements
    attributes:
      label: Suggested Improvements
      description: Please provide your suggestions for how we can improve the documentation. Be as specific as possible.
      placeholder: Your suggestions for improvement...
    validations:
      required: true

  - type: textarea
    id: additional-resources
    attributes:
      label: Additional Resources or References
      description: If applicable, provide any additional resources, references, or external documentation that support your suggestions.
      placeholder: URL to resources or external documentation.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this documentation improvement suggestion, you agree to follow our [Code of Conduct](https://mediaease.github.io/docs/CODE_OF_CONDUCT/)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
