name: Feature Request
description: Suggest an idea for this project
title: "feat: "
labels: ["enhancement"]
assignees: tomcdj71
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature for this project!

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we reach you for further discussion about your feature request?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: input
    id: feature-summary
    attributes:
      label: Feature Summary
      description: Please provide a brief summary of your feature request.
      placeholder: Brief summary of the feature.
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Detailed Feature Description
      description: Please describe in detail the feature you would like to see implemented. Include any specific functionality and its benefits.
      placeholder: Describe the feature in detail...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Please provide any additional context or screenshots about the feature request here.
      placeholder: Add any other context or screenshots about the feature request here.
    validations:
      required: false
    
  - type: textarea
    id: documentation-links
    attributes:
      label: Documentation Links
      description: Please provide links to any relevant documentation, Git repository, or other resources that could be helpful.
      placeholder: URL to documentation, Git repository, etc.
    validations:
      required: false
      
  - type: markdown
    attributes:
      value: |
        **If the feature request is approved, would you be willing to submit a PR?**
        (Help can be provided if you need assistance submitting a PR)

  - type: checkboxes
    id: willing-to-submit-pr
    attributes:
      label: Willingness to Submit a PR
      options:
        - label: Yes, I am willing to submit a PR.
          required: false
        - label: No, I am not able to submit a PR.
          required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this feature request, you agree to follow our [Code of Conduct](https://mediaease.github.io/docs/CODE_OF_CONDUCT/)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
