name: Update Documentation

on:
  push:
    # branches:
    #   - main
    # paths:
    #   - "docs/**"
    #   - "scripts/docs/**"
    #   - "harmonyui/docs/**"
  pull_request:
    branches:
      - main
    paths:
      - "docs/**"
      - "scripts/docs/**"
      - "harmonyui/docs/**"

jobs:
  documentation-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Verify 'docs-needed' Label
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v5
        with:
          script: |
            const payload = context.payload.pull_request
            const labelFound = payload.labels.some(label => label.name === 'docs-needed');
            if (labelFound) {
              core.setFailed("Pull request has 'docs-needed' label.");
            }

      - name: Clone mflibs Repository
        run: |
          git clone https://github.com/MediaEase/mflibs.git mflibs/

      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Python Dependencies
        run: pip install pyyaml

      - name: Install APT dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gawk make
          git clone --recursive https://github.com/reconquest/shdoc
          cd shdoc
          sudo make install
          cd

      - name: Clone Documentation Repository
        run: |
          git clone https://github.com/MediaEase/docs.git tmp/

      - name: Update Documentation with READMEs
        run: |
          rm -rf tmp/docs/mediaease/components/api/openapi.yaml
          mkdir -p tmp/docs/mediaease
          mkdir -p tmp/docs/mediaease/components
          mkdir -p tmp/docs/mediaease/components/harmonyui
          mkdir -p tmp/docs/mediaease/components/zen
          mkdir -p tmp/docs/mediaease/components/api
          mkdir -p tmp/docs/mediaease/components/mflibs
          chmod +x .github/scripts/auto-docs.sh
          ./.github/scripts/auto-docs.sh zen/src
          if [ -d "tmp/docs/mediaease/components/zen/src" ]; then
            mv tmp/docs/mediaease/components/zen/src/* tmp/docs/mediaease/components/zen/
            rm -rf tmp/docs/mediaease/components/zen/src
          fi
          cp -pR harmonyui/config/packages/nelmio_api_doc.yaml tmp/docs/mediaease/components/api
          cp -pR docs/* tmp/docs/mediaease
          cp -pR harmonyui/docs/* tmp/docs/mediaease/components/harmonyui
          cp -pR zen/docs/* tmp/docs/mediaease/components/zen
          cp -pR mflibs/docs/* tmp/docs/mediaease/components/mflibs
          cp -pR mflibs/readme.md tmp/docs/mediaease/components/mflibs/README.md
          cp -pR README.md tmp/docs/mediaease
          cp -pR harmonyui/README.md tmp/docs/mediaease/components/harmonyui/
          cp -pR zen/README.md tmp/docs/mediaease/components/zen/
          if [ -d "tmp/docs/mediaease/docs/" ]; then
            rm -rf tmp/docs/mediaease/docs
          fi
          tree -L 2 tmp/docs/mediaease
      # get the current HarmonyUI version from the harmonyui repository main branch
      - name: Format README Files
        run: |
          python .github/scripts/mkdocs.py
          python .github/scripts/openapi.py
          HARMONYUI_VERSION=$(git -C harmonyui tag --list 'v*' | grep -vE '(-beta|-alpha)' | xargs -I {} git -C harmonyui rev-list -n 1 {} | xargs git -C harmonyui describe --tags --exact-match 2>/dev/null || echo "unknown")
          HARMONYUI_VERSION=$(echo $HARMONYUI_VERSION | sed -E 's/^v//')
          sed -i "s/version: .*/version: $HARMONYUI_VERSION/g" ./openapi.yaml
          sed -i '/url:/d' ./openapi.yaml
          sed -i '/^servers:$/d; /^ *description: Local development server$/d; /^  license:$/!b;n;c\    name: MIT\n    url: https://opensource.org/licenses/MIT' ./openapi.yaml
          if [ -f "tmp/docs/mediaease/components/api/openapi.yaml" ]; then
            rm -rf tmp/docs/mediaease/components/api/openapi.yaml
          fi
          if [ -f "tmp/docs/mediaease/components/api/nelmio_api_doc.yaml" ]; then
            rm -rf tmp/docs/mediaease/components/api/nelmio_api_doc.yaml
          fi
          mv ./openapi.yaml tmp/docs/mediaease/components/api/openapi.yaml
          chmod +x .github/scripts/format-alerts.sh
          ./.github/scripts/format-alerts.sh

      - name: Last edits
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: |
            lint tmp/docs/mediaease/components/api/openapi.yaml
            bundle docs/mediaease/components/api/openapi.yaml --output tmp/docs/mediaease/components/api/dist.json

      - name: Check for Documentation Changes
        id: check_changes
        run: |
          cd tmp/
          git add .
          if git diff --staged --quiet; then
            echo "No changes to documentation. Exiting workflow."
            exit 0
          fi

      - name: Commit and Push Documentation Changes
        if: github.event_name == 'push' && ${{ contains(github.ref, 'main') }}
        run: |
          echo "Committing and pushing changes."
          cd tmp/
          git config user.name "MediaEase Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "docs: update documentation [automated]"
          git push --set-upstream https://x-access-token:${{ secrets.MEDIAEASE_ACCESS_TOKEN }}@github.com/MediaEase/docs HEAD
