name: Detect Release Type

on:
  push:
    branches:
      - main
      - develop

jobs:
  detect_release_type:
    runs-on: ubuntu-latest
    steps:
      - name: Set Release Type
        run: echo "RELEASE_TYPE=${{ github.ref == 'refs/heads/develop' && 'pre-release' || 'release' }}" >> $GITHUB_ENV
